version: '3.8'

services:

  # Web Server Service
  user_nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - users_app
      - users_db

  #Database Service
  users_db:
    image : mysql
    container_name : users_db
    volumes:
      - ./mysql/data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: Users
      MYSQL_ROOT_PASSWORD: password
  

  # Application Service
  users_app:
    container_name: users_app
    build: 
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www
    ports:
      - "9000:9000"
    working_dir: /var/www

  #phpMyAdmin Service
  users_phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: users_phpmyadmin
    ports:
      - "5050:80"
    depends_on:
      - users_db
  